In [2]:
from pathlib import Path
import datetime
import os
import random
import re
import shutil
import time

import dagshub
import matplotlib.pyplot as plt
import mlflow
import pandas as pd
import torch
from IPython.display import display
from roboflow import Roboflow
from ultralytics import YOLO, settings

In [3]:
rf = Roboflow(api_key="MQdx0fMQ8FiQPaS1VHRH")
project = rf.workspace("abiya-thesis").project("plant-pathology-2021-object-detection-j1jvh")
version = project.version(12)
dataset = version.download("yolov12", location="dataset")

loading Roboflow workspace...
loading Roboflow project...

Downloading Dataset Version Zip in dataset to yolov12:: 100%|██████████| 542799/542799 [00:47<00:00, 11326.03it/s]

Extracting Dataset Version Zip to dataset in yolov12:: 100%|██████████| 21854/21854 [00:12<00:00, 1706.38it/s]

In [3]:
source_root = Path(getattr(globals().get("dataset", None), "location", "dataset"))
output_root = Path("split-dataset")

# dataset_sizes = [750, 1000, 1250, 1500, 1750, 2000, 3000, 4000, 5000]
dataset_sizes = [100, 200, 300, 400, 500, 600, 700]
seed = 42
class_names = ["frog-eye-leaf-spot", "healthy", "rust"]
img_exts = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}

def get_label_path(img_path: Path) -> Path | None:
    parts = list(img_path.parts)
    if "images" not in parts:
        return None
    idx = parts.index("images")
    parts[idx] = "labels"
    return Path(*parts).with_suffix(".txt")

def flatten_name(path: Path) -> str:
    return str(path.with_suffix("")).replace("\\", "__").replace("/", "__")

def write_split_yaml(split_dir: Path, names: list[str]) -> None:
    names_text = "[" + ", ".join(repr(name) for name in names) + "]"
    yaml_text = (
        f"path: {split_dir.resolve().as_posix()}\n"
        "train: train/images\n"
        "val: val/images\n"
        "test: test/images\n\n"
        f"nc: {len(names)}\n"
        f"names: {names_text}\n"
    )
    (split_dir / "data.yaml").write_text(yaml_text, encoding="utf-8")

# Kumpulkan pasangan image-label yang valid
pairs = []
for img_path in source_root.rglob("*"):
    if img_path.is_file() and img_path.suffix.lower() in img_exts:
        if "split-dataset" in img_path.parts:
            continue
        label_path = get_label_path(img_path)
        if label_path is not None and label_path.exists():
            pairs.append((img_path, label_path))

random.Random(seed).shuffle(pairs)

total_available = len(pairs)
print(f"Total pasangan image-label tersedia: {total_available}")

for split_size in dataset_sizes:
    if split_size > total_available:
        print(f"Ukuran {split_size} dilewati karena data hanya tersedia {total_available}.")
        continue

    train_count = int(split_size * 0.7)
    val_count = int(split_size * 0.1)

    subset = pairs[:split_size]
    train_pairs = subset[:train_count]
    val_pairs = subset[train_count:train_count + val_count]
    test_pairs = subset[train_count + val_count:]

    split_dir = output_root / str(split_size)
    for split_name in ["train", "val", "test"]:
        (split_dir / split_name / "images").mkdir(parents=True, exist_ok=True)
        (split_dir / split_name / "labels").mkdir(parents=True, exist_ok=True)

    def copy_pairs(pairs_list, split_name):
        for img_path, label_path in pairs_list:
            base_name = flatten_name(img_path.relative_to(source_root))
            dst_img = split_dir / split_name / "images" / f"{base_name}{img_path.suffix.lower()}"
            dst_lbl = split_dir / split_name / "labels" / f"{base_name}.txt"
            shutil.copy2(img_path, dst_img)
            shutil.copy2(label_path, dst_lbl)

    copy_pairs(train_pairs, "train")
    copy_pairs(val_pairs, "val")
    copy_pairs(test_pairs, "test")
    write_split_yaml(split_dir, class_names)

    print(
        f"Selesai {split_size}: train={len(train_pairs)}, val={len(val_pairs)}, test={len(test_pairs)} -> {split_dir}"
    )

Total pasangan image-label tersedia: 10921
Selesai 100: train=70, val=10, test=20 -> split-dataset\100
Selesai 200: train=140, val=20, test=40 -> split-dataset\200
Selesai 300: train=210, val=30, test=60 -> split-dataset\300
Selesai 400: train=280, val=40, test=80 -> split-dataset\400
Selesai 500: train=350, val=50, test=100 -> split-dataset\500
Selesai 600: train=420, val=60, test=120 -> split-dataset\600
Selesai 700: train=489, val=70, test=141 -> split-dataset\700

In [4]:
# ML Flow dan DagsHub Integration
dagshub.init(repo_owner='abiyamf', repo_name='thesis', mlflow=True)
settings.update({"mlflow": True})

Accessing as abiyamf

Initialized MLflow to track repo "abiyamf/thesis"

Repository abiyamf/thesis initialized!

In [5]:
os.environ["MLFLOW_KEEP_RUN_ACTIVE"] = "True"
gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "cpu"

def format_duration(seconds: float) -> str:
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    return f"{hours}h {minutes}m {secs}s"

def save_class_metrics(val_results, mode):
    names = val_results.names
    data = {
        "class": [names[i] for i in range(len(names))],
        "precision": val_results.box.p.tolist(),
        "recall": val_results.box.r.tolist(),
        "mAP50": val_results.box.ap50.tolist(),
        "mAP50-95": val_results.box.maps.tolist(),
    }

    all_row = {
        "class": "all",
        "precision": float(val_results.box.mp),
        "recall": float(val_results.box.mr),
        "mAP50": float(val_results.box.map50),
        "mAP50-95": float(val_results.box.map),
    }

    for key in data.keys():
        data[key].insert(0, all_row[key])

    df = pd.DataFrame(data)
    csv_path = Path(val_results.save_dir) / f"class_metrics_{mode}.csv"
    df.to_csv(csv_path, index=False)

    return str(csv_path)

def write_validation_summary(result, csv_path: Path) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    csv_path.write_text(result.to_csv(), encoding="utf-8")

def read_map_metrics(csv_path: Path) -> tuple[float, float]:
    df = pd.read_csv(csv_path)
    if "class" in df.columns:
        class_col = "class"
    elif "Class" in df.columns:
        class_col = "Class"
    else:
        class_col = None

    if class_col is not None and (df[class_col].astype(str).str.lower() == "all").any():
        row = df[df[class_col].astype(str).str.lower() == "all"].iloc[0]
        return float(row["mAP50"]), float(row["mAP50-95"])

    # Fallback untuk file hasil result.to_csv() YOLO yang hanya berisi baris per class.
    return float(df["mAP50"].mean()), float(df["mAP50-95"].mean())

def build_summary_from_validation_files(project_base: Path) -> pd.DataFrame:
    summary_dir = project_base / "validation" / "summary"
    pattern = re.compile(r"(?P<model_size>.+)-split-(?P<split_size>\d+)-(?P<mode>train|test)-metrics\.csv$")
    rows = {}

    for csv_path in summary_dir.glob("*-metrics.csv"):
        match = pattern.match(csv_path.name)
        if match is None:
            continue

        model_size = match.group("model_size")
        split_size = int(match.group("split_size"))
        mode = match.group("mode")
        map50, map50_95 = read_map_metrics(csv_path)
        key = (model_size, split_size)
        rows.setdefault(key, {"model_size": model_size, "split_size": split_size})
        rows[key][f"{mode}_mAP50"] = map50
        rows[key][f"{mode}_mAP50_95"] = map50_95

    summary_df = pd.DataFrame(rows.values())
    if summary_df.empty:
        return summary_df

    summary_df = summary_df.dropna(subset=["train_mAP50", "test_mAP50"])
    return summary_df.sort_values(["model_size", "split_size"]).reset_index(drop=True)

def save_and_plot_summary(summary_df: pd.DataFrame, project_base: Path) -> None:
    if summary_df.empty:
        print("Belum ada metrik train/test yang bisa divisualisasikan.")
        return

    summary_csv = project_base / "training_summary_by_split.csv"
    summary_csv.parent.mkdir(parents=True, exist_ok=True)
    summary_df.to_csv(summary_csv, index=False)
    display(summary_df)

    plt.figure(figsize=(10, 6))
    for model_size, group in summary_df.groupby("model_size"):
        group = group.sort_values("split_size")
        plt.plot(group["split_size"], group["train_mAP50"], marker="o", label=f"Train {model_size}")
        plt.plot(group["split_size"], group["test_mAP50"], marker="s", linestyle="--", label=f"Test {model_size}")

    plt.title("Kenaikan Akurasi Train dan Test per Split Data")
    plt.xlabel("Jumlah data pada split")
    plt.ylabel("Akurasi (mAP50)")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    accuracy_plot = project_base / "accuracy_by_split.png"
    plt.savefig(accuracy_plot, dpi=200)
    plt.show()

    print(f"Ringkasan disimpan ke: {summary_csv}")
    print(f"Plot akurasi disimpan ke: {accuracy_plot}")

In [8]:
# Variabel Global
projectType = "feedback_reviewer"
imgsz = 640
model_configs = [("yolo12n.pt", "nano")]
epochs = 50
batch = 16
data_path = Path("split-dataset")
project_base = Path("results/yolo_v12/feedback_reviewer")
available_splits = sorted(
    [p for p in data_path.iterdir() if p.is_dir() and (p / "data.yaml").exists()],
    key=lambda p: int(p.name),
)
available_splits = available_splits[:7]
print("Split yang akan dilatih:", [p.name for p in available_splits])

Split yang akan dilatih: ['100', '200', '300', '400', '500', '600', '700']

In [9]:
mlflow.set_experiment(f"thesis-{projectType}")
training_summaries = build_summary_from_validation_files(project_base).to_dict("records")
completed_splits = {
    (row["model_size"], int(row["split_size"]))
    for row in training_summaries
    if pd.notna(row.get("train_mAP50")) and pd.notna(row.get("test_mAP50"))
}

for model_name, model_size in model_configs:
    for split_dir in available_splits:
        split_size = int(split_dir.name)
        if (model_size, split_size) in completed_splits:
            print(f"Lewati {model_size} split {split_size}: metrik train/test sudah ada.")
            continue

        data_yaml = split_dir / "data.yaml"
        time_now = datetime.datetime.now().strftime("%m-%d_%H-%M-%S")
        run_name = f"{model_size}-split-{split_size}-{time_now}"
        model = YOLO(model_name)

        with mlflow.start_run(run_name=run_name):
            mlflow.log_params({
                "project_type": projectType,
                "model": model_name,
                "model_size": model_size,
                "split_size": split_size,
                "data_yaml": str(data_yaml),
                "gpu": gpu_name,
                "epochs": epochs,
                "batch": batch,
                "imgsz": imgsz,
            })

            start_time = time.time()
            training = model.train(
                data=str(data_yaml),
                epochs=epochs,
                imgsz=imgsz,
                batch=batch,
                project=str(project_base / "training" / model_size),
                name=f"split_{split_size}",
                exist_ok=True,
                plots=True,
            )
            elapsed = time.time() - start_time

            best_weights = Path(training.save_dir) / "weights" / "best.pt"
            trained_model = YOLO(str(best_weights if best_weights.exists() else model_name))

            train_eval = trained_model.val(
                data=str(data_yaml),
                imgsz=imgsz,
                project=str(project_base / "validation" / model_size),
                name=f"split_{split_size}_train",
                exist_ok=True,
                split="train",
            )
            test_eval = trained_model.val(
                data=str(data_yaml),
                imgsz=imgsz,
                project=str(project_base / "validation" / model_size),
                name=f"split_{split_size}_test",
                exist_ok=True,
                split="test",
            )

            summary_dir = project_base / "validation" / "summary"
            write_validation_summary(train_eval, summary_dir / f"{model_size}-split-{split_size}-train-metrics.csv")
            write_validation_summary(test_eval, summary_dir / f"{model_size}-split-{split_size}-test-metrics.csv")

            train_class_metrics = save_class_metrics(train_eval, "train")
            test_class_metrics = save_class_metrics(test_eval, "test")
            mlflow.log_artifact(train_class_metrics, artifact_path="class_metrics")
            mlflow.log_artifact(test_class_metrics, artifact_path="class_metrics")

            metrics = {
                "train_mAP50": float(train_eval.box.map50),
                "train_mAP50_95": float(train_eval.box.map),
                "test_mAP50": float(test_eval.box.map50),
                "test_mAP50_95": float(test_eval.box.map),
            }
            mlflow.log_metrics(metrics)
            mlflow.log_param("training_time", format_duration(elapsed))

            print(
                f"Selesai {model_size} split {split_size}: "
                f"train mAP50={metrics['train_mAP50']:.4f}, test mAP50={metrics['test_mAP50']:.4f}"
            )

        # Simpan ulang summary dan plot setelah setiap split selesai.
        summary_df = build_summary_from_validation_files(project_base)
        save_and_plot_summary(summary_df, project_base)
        completed_splits.add((model_size, split_size))

New https://pypi.org/project/ultralytics/8.4.46 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.0  Python-3.12.12 torch-2.9.1+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 16303MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=split-dataset\100\data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=split_100, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=results\yolo_v12\feedback_reviewer\training\nano, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_100, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1     86912  ultralytics.nn.modules.block.A2C2f           [384, 128, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     24000  ultralytics.nn.modules.block.A2C2f           [256, 64, 1, False, -1]
 15                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     74624  ultralytics.nn.modules.block.A2C2f           [192, 128, 1, False, -1]
 18                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 21        [14, 17, 20]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLOv12n summary: 272 layers, 2,568,633 parameters, 2,568,617 gradients, 6.5 GFLOPs

Transferred 640/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 26.0MB/s 0.2s.2s<0.0s.5s
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 8.82.0 MB/s, size: 50.6 KB)
train: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\100\train\labels... 70 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 70/70 616.8it/s 0.1s0.1s
train: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\100\train\labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.00.0 ms, read: 6.51.4 MB/s, size: 45.1 KB)
val: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\100\val\labels... 10 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 10/10 328.5it/s 0.0s
val: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\100\val\labels.cache
Plotting labels to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_100\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: MuSGD(lr=0.001429, momentum=0.9) with parameter groups 0 weight(decay=0.0), 0 weight(decay=0.0005), 0 bias(decay=0.0)
MLflow: logging run_id(901561edf1724fea83c4117aacaf7dd3) to https://dagshub.com/abiyamf/thesis.mlflow
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_100
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      3.41G      1.104      3.189      1.642         24        640: 100% ━━━━━━━━━━━━ 5/5 1.4s/it 7.1s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5it/s 0.7s
                   all         10         24    0.00989      0.895     0.0982     0.0214

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.43G      1.138       3.21      1.693         18        640: 100% ━━━━━━━━━━━━ 5/5 3.8it/s 1.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.8it/s 0.1s
                   all         10         24     0.0105      0.947     0.0403      0.015

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.45G      1.007      3.192       1.53         22        640: 100% ━━━━━━━━━━━━ 5/5 4.1it/s 1.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.7it/s 0.1s
                   all         10         24     0.0104      0.974      0.057     0.0178

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.46G     0.9047      3.141      1.475         18        640: 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.5it/s 0.1s
                   all         10         24    0.00957      0.947     0.0793     0.0375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.48G     0.8681      3.091      1.452         34        640: 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.4it/s 0.1s
                   all         10         24    0.00865      0.921      0.119     0.0819

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.49G     0.7502      3.091      1.365         21        640: 100% ━━━━━━━━━━━━ 5/5 6.1it/s 0.8s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.0it/s 0.1s
                   all         10         24    0.00804      0.895      0.173      0.124

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.51G     0.7388      3.066      1.336         23        640: 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.9it/s 0.1s
                   all         10         24    0.00774      0.895      0.241       0.16

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.52G     0.7224      2.999      1.337         26        640: 100% ━━━━━━━━━━━━ 5/5 6.2it/s 0.8s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.0it/s 0.1s
                   all         10         24    0.00858      0.947      0.283      0.215

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.54G     0.7232      2.975      1.323         25        640: 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.4it/s 0.1s
                   all         10         24    0.00934      0.974      0.265      0.225

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.55G     0.6692      2.967      1.289         21        640: 100% ━━━━━━━━━━━━ 5/5 6.0it/s 0.8s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.3it/s 0.1s
                   all         10         24    0.00956      0.974      0.256      0.225

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.56G     0.6061      2.949      1.208         27        640: 100% ━━━━━━━━━━━━ 5/5 6.1it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.0it/s 0.1s
                   all         10         24    0.00989          1      0.288      0.256

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.59G     0.6082       2.93      1.244         25        640: 100% ━━━━━━━━━━━━ 5/5 6.1it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.0it/s 0.1s
                   all         10         24       0.01          1      0.309      0.271

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50       3.6G     0.5432      2.875      1.199         30        640: 100% ━━━━━━━━━━━━ 5/5 7.4it/s 0.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.0it/s 0.1s
                   all         10         24     0.0103          1      0.372      0.339

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.61G     0.6193      2.878      1.199         29        640: 100% ━━━━━━━━━━━━ 5/5 6.2it/s 0.8s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.4it/s 0.1s
                   all         10         24     0.0108          1      0.482      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.63G     0.5755      2.872      1.207         22        640: 100% ━━━━━━━━━━━━ 5/5 6.0it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.5it/s 0.1s
                   all         10         24     0.0106      0.974      0.511      0.467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.64G     0.6218      2.815      1.227         25        640: 100% ━━━━━━━━━━━━ 5/5 7.2it/s 0.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.7it/s 0.1s
                   all         10         24     0.0107      0.974      0.472      0.432

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.65G      0.553      2.761      1.172         25        640: 100% ━━━━━━━━━━━━ 5/5 6.0it/s 0.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.2it/s 0.1s
                   all         10         24     0.0107      0.974      0.481       0.45

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.67G     0.5675      2.772       1.17         34        640: 100% ━━━━━━━━━━━━ 5/5 6.8it/s 0.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.7it/s 0.1s
                   all         10         24     0.0111          1      0.454      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.69G     0.5497      2.729      1.147         19        640: 100% ━━━━━━━━━━━━ 5/5 7.5it/s 0.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.8it/s 0.1s
                   all         10         24     0.0108          1      0.499      0.439

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50       3.7G     0.5479       2.67      1.153         25        640: 100% ━━━━━━━━━━━━ 5/5 6.1it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 15.0it/s 0.1s
                   all         10         24     0.0109          1      0.489      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.71G     0.5876      2.647      1.158         24        640: 100% ━━━━━━━━━━━━ 5/5 7.4it/s 0.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.1it/s 0.1s
                   all         10         24      0.402      0.155      0.453      0.394

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.73G     0.5777      2.602       1.18         26        640: 100% ━━━━━━━━━━━━ 5/5 7.4it/s 0.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.4it/s 0.1s
                   all         10         24      0.554      0.329      0.457      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.75G      0.534      2.565      1.148         20        640: 100% ━━━━━━━━━━━━ 5/5 7.4it/s 0.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 16.1it/s 0.1s
                   all         10         24      0.514      0.479      0.445      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.76G     0.5083       2.54      1.153         20        640: 100% ━━━━━━━━━━━━ 5/5 5.8it/s 0.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.7it/s 0.1s
                   all         10         24      0.487      0.575      0.435      0.392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.77G     0.5475      2.549      1.133         27        640: 100% ━━━━━━━━━━━━ 5/5 7.5it/s 0.7s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.8it/s 0.1s
                   all         10         24      0.478      0.601      0.429       0.39

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.79G     0.5963      2.507      1.177         22        640: 100% ━━━━━━━━━━━━ 5/5 7.1it/s 0.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 14.2it/s 0.1s
                   all         10         24      0.494      0.593      0.479      0.437

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      3.81G     0.5526      2.452      1.141         30        640: 100% ━━━━━━━━━━━━ 5/5 5.9it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.9it/s 0.1s
                   all         10         24      0.496      0.605      0.482      0.433

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.82G     0.5164      2.416      1.117         26        640: 100% ━━━━━━━━━━━━ 5/5 5.0it/s 1.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.1it/s 0.1s
                   all         10         24      0.486      0.637      0.481      0.429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      3.83G      0.543      2.435      1.151         28        640: 100% ━━━━━━━━━━━━ 5/5 6.5it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.3it/s 0.1s
                   all         10         24      0.493      0.636      0.471      0.425

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      3.85G     0.5431      2.399      1.122         24        640: 100% ━━━━━━━━━━━━ 5/5 6.5it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.1it/s 0.1s
                   all         10         24       0.47      0.637      0.464      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      3.87G     0.5589      2.396      1.098         38        640: 100% ━━━━━━━━━━━━ 5/5 5.9it/s 0.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.1it/s 0.1s
                   all         10         24      0.463      0.637      0.468      0.423

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      3.88G     0.5261      2.326       1.11         31        640: 100% ━━━━━━━━━━━━ 5/5 5.8it/s 0.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.5it/s 0.1s
                   all         10         24      0.501      0.635      0.506      0.456

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,750,0.930803,0.851967,0.986920,0.965513
2,nano,1000,0.905773,0.839843,0.986080,0.963213
3,nano,1250,0.957177,0.901227,0.989087,0.966697
4,nano,1500,0.964817,0.918633,0.985893,0.964907
5,nano,1750,0.942217,0.894710,0.988663,0.967827
6,nano,2000,0.940753,0.896000,0.988143,0.967657
7,nano,3000,0.960183,0.914897,0.986400,0.964483
8,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png
New https://pypi.org/project/ultralytics/8.4.46 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.0  Python-3.12.12 torch-2.9.1+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 16303MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=split-dataset\200\data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=split_200, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=results\yolo_v12\feedback_reviewer\training\nano, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_200, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1     86912  ultralytics.nn.modules.block.A2C2f           [384, 128, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     24000  ultralytics.nn.modules.block.A2C2f           [256, 64, 1, False, -1]
 15                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     74624  ultralytics.nn.modules.block.A2C2f           [192, 128, 1, False, -1]
 18                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 21        [14, 17, 20]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLOv12n summary: 272 layers, 2,568,633 parameters, 2,568,617 gradients, 6.5 GFLOPs

Transferred 640/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 8.31.6 MB/s, size: 48.9 KB)
train: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\200\train\labels... 140 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 140/140 860.2it/s 0.2s2s
train: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\200\train\labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.20.1 ms, read: 5.61.4 MB/s, size: 48.1 KB)
val: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\200\val\labels... 20 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 20/20 386.3it/s 0.1s
val: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\200\val\labels.cache
Plotting labels to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_200\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: MuSGD(lr=0.001429, momentum=0.9) with parameter groups 0 weight(decay=0.0), 0 weight(decay=0.0005), 0 bias(decay=0.0)
MLflow: logging run_id(3606f91914ca4b7c8e53127daf37bb25) to https://dagshub.com/abiyamf/thesis.mlflow
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_200
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      3.72G      1.153      3.213       1.65         68        640: 100% ━━━━━━━━━━━━ 9/9 1.4it/s 6.4s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4it/s 0.7s
                   all         20         47    0.00644      0.937      0.102     0.0515

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.72G     0.9976      3.185      1.533         57        640: 100% ━━━━━━━━━━━━ 9/9 4.3it/s 2.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.1it/s 0.1s
                   all         20         47    0.00641      0.955      0.182      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.72G     0.8292      3.119      1.409         47        640: 100% ━━━━━━━━━━━━ 9/9 5.3it/s 1.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.0it/s 0.1s
                   all         20         47    0.00656      0.964      0.216       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.72G     0.6901       3.06      1.297         51        640: 100% ━━━━━━━━━━━━ 9/9 5.8it/s 1.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.8it/s 0.1s
                   all         20         47    0.00675      0.964      0.278      0.233

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.72G     0.6564      2.995      1.261         66        640: 100% ━━━━━━━━━━━━ 9/9 5.2it/s 1.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.4it/s 0.1s
                   all         20         47    0.00686      0.955      0.234      0.176

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.72G     0.6989      2.988      1.308         49        640: 100% ━━━━━━━━━━━━ 9/9 5.8it/s 1.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.8it/s 0.1s
                   all         20         47     0.0074      0.982       0.31      0.244

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.72G     0.5967      2.883      1.214         45        640: 100% ━━━━━━━━━━━━ 9/9 6.4it/s 1.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.2it/s 0.1s
                   all         20         47    0.00766      0.991       0.37      0.311

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.72G     0.5695      2.822       1.19         53        640: 100% ━━━━━━━━━━━━ 9/9 6.3it/s 1.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.9it/s 0.1s
                   all         20         47    0.00735      0.982      0.462      0.415

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.72G     0.5882      2.768      1.177         41        640: 100% ━━━━━━━━━━━━ 9/9 6.3it/s 1.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.5it/s 0.1s
                   all         20         47    0.00786          1      0.338      0.282

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.72G     0.5512      2.678      1.139         43        640: 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.9it/s 0.1s
                   all         20         47    0.00816          1      0.333      0.285

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.72G     0.5281      2.634      1.112         57        640: 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.1it/s 0.1s
                   all         20         47      0.606      0.373      0.342      0.291

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.72G     0.5668      2.566      1.153         52        640: 100% ━━━━━━━━━━━━ 9/9 6.1it/s 1.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.8it/s 0.1s
                   all         20         47      0.652      0.342      0.373      0.325

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      3.72G     0.5967      2.488      1.166         52        640: 100% ━━━━━━━━━━━━ 9/9 7.1it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.1it/s 0.1s
                   all         20         47      0.617      0.372      0.378      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.72G     0.5866      2.389      1.152         61        640: 100% ━━━━━━━━━━━━ 9/9 7.1it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.4it/s 0.1s
                   all         20         47      0.614      0.436      0.366      0.333

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.72G     0.5852      2.329      1.158         66        640: 100% ━━━━━━━━━━━━ 9/9 7.1it/s 1.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.0it/s 0.1s
                   all         20         47      0.623      0.418      0.427      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.74G     0.5349      2.266      1.108         52        640: 100% ━━━━━━━━━━━━ 9/9 6.1it/s 1.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.0it/s 0.1s
                   all         20         47      0.656      0.435      0.453      0.429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.75G     0.6035      2.118      1.163         45        640: 100% ━━━━━━━━━━━━ 9/9 7.0it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.3it/s 0.1s
                   all         20         47      0.631      0.491      0.449      0.429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.77G     0.5685      2.104      1.126         49        640: 100% ━━━━━━━━━━━━ 9/9 7.0it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.4it/s 0.1s
                   all         20         47      0.736      0.359      0.491      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.78G     0.5547      1.959      1.117         60        640: 100% ━━━━━━━━━━━━ 9/9 6.6it/s 1.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.6it/s 0.1s
                   all         20         47      0.744      0.464      0.508      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50       3.8G     0.5421      1.823       1.12         46        640: 100% ━━━━━━━━━━━━ 9/9 6.2it/s 1.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.3it/s 0.1s
                   all         20         47      0.798      0.472      0.516      0.478

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.81G     0.5762      1.782      1.159         55        640: 100% ━━━━━━━━━━━━ 9/9 7.1it/s 1.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.2it/s 0.1s
                   all         20         47      0.775      0.493      0.539      0.495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.83G     0.5154      1.683      1.086         49        640: 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.2it/s 0.1s
                   all         20         47      0.893      0.448      0.547      0.499

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.84G      0.501      1.657      1.091         49        640: 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.6it/s 0.1s
                   all         20         47      0.877      0.441      0.549      0.503

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.86G      0.528      1.595      1.112         38        640: 100% ━━━━━━━━━━━━ 9/9 6.3it/s 1.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.7it/s 0.1s
                   all         20         47      0.803      0.499      0.549      0.503

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.87G     0.5409      1.545      1.123         42        640: 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.3it/s 0.1s
                   all         20         47      0.813      0.502      0.557      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.88G     0.4859      1.376      1.081         47        640: 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.7it/s 0.1s
                   all         20         47      0.921      0.475      0.568      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50       3.9G     0.4929      1.404      1.096         47        640: 100% ━━━━━━━━━━━━ 9/9 7.2it/s 1.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.3it/s 0.1s
                   all         20         47      0.918      0.488      0.573      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.91G     0.4614      1.356      1.078         54        640: 100% ━━━━━━━━━━━━ 9/9 6.4it/s 1.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.4it/s 0.1s
                   all         20         47      0.918      0.494      0.585      0.541

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      3.93G     0.4892      1.378      1.067         58        640: 100% ━━━━━━━━━━━━ 9/9 6.9it/s 1.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.9it/s 0.1s
                   all         20         47      0.955      0.492      0.599      0.549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      3.94G     0.5004      1.419      1.108         53        640: 100% ━━━━━━━━━━━━ 9/9 6.8it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.1it/s 0.1s
                   all         20         47      0.862      0.529      0.591      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      3.96G     0.4599      1.301      1.053         50        640: 100% ━━━━━━━━━━━━ 9/9 7.0it/s 1.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.0it/s 0.1s
                   all         20         47      0.878      0.519      0.593      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      3.97G      0.468      1.283      1.075         42        640: 100% ━━━━━━━━━━━━ 9/9 6.3it/s 1.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.9it/s 0.1s
                   all         20         47      0.845      0.512      0.592      0.551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,200,0.760120,0.728120,0.979800,0.963590
2,nano,750,0.930803,0.851967,0.986920,0.965513
3,nano,1000,0.905773,0.839843,0.986080,0.963213
4,nano,1250,0.957177,0.901227,0.989087,0.966697
5,nano,1500,0.964817,0.918633,0.985893,0.964907
6,nano,1750,0.942217,0.894710,0.988663,0.967827
7,nano,2000,0.940753,0.896000,0.988143,0.967657
8,nano,3000,0.960183,0.914897,0.986400,0.964483
9,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png
New https://pypi.org/project/ultralytics/8.4.46 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.0  Python-3.12.12 torch-2.9.1+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 16303MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=split-dataset\300\data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=split_300, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=results\yolo_v12\feedback_reviewer\training\nano, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_300, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1     86912  ultralytics.nn.modules.block.A2C2f           [384, 128, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     24000  ultralytics.nn.modules.block.A2C2f           [256, 64, 1, False, -1]
 15                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     74624  ultralytics.nn.modules.block.A2C2f           [192, 128, 1, False, -1]
 18                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 21        [14, 17, 20]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLOv12n summary: 272 layers, 2,568,633 parameters, 2,568,617 gradients, 6.5 GFLOPs

Transferred 640/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 9.62.2 MB/s, size: 52.5 KB)
train: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\300\train\labels... 210 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 210/210 1.0Kit/s 0.2s<0.3s
train: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\300\train\labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.30.0 ms, read: 5.71.2 MB/s, size: 46.1 KB)
val: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\300\val\labels... 30 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 30/30 384.2it/s 0.1s
val: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\300\val\labels.cache
Plotting labels to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_300\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: MuSGD(lr=0.001429, momentum=0.9) with parameter groups 0 weight(decay=0.0), 0 weight(decay=0.0005), 0 bias(decay=0.0)
MLflow: logging run_id(fc5588c034764f408486de93e1f3f05b) to https://dagshub.com/abiyamf/thesis.mlflow
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_300
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      3.87G      1.101       3.27      1.658          4        640: 100% ━━━━━━━━━━━━ 14/14 1.1it/s 12.3s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2it/s 0.9s
                   all         30         68    0.00629      0.932     0.0379     0.0161

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.87G     0.8671      3.122      1.417         16        640: 100% ━━━━━━━━━━━━ 14/14 4.3it/s 3.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.6it/s 0.2s
                   all         30         68    0.00671      0.959      0.113     0.0908

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.87G     0.7283      3.038      1.313          9        640: 100% ━━━━━━━━━━━━ 14/14 4.5it/s 3.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.7it/s 0.2s
                   all         30         68    0.00761      0.966      0.203      0.155

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.87G     0.6674      2.958      1.279         12        640: 100% ━━━━━━━━━━━━ 14/14 5.0it/s 2.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.7it/s 0.2s
                   all         30         68    0.00853       0.98      0.235      0.194

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.87G     0.6247      2.843      1.207         16        640: 100% ━━━━━━━━━━━━ 14/14 5.3it/s 2.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.3it/s 0.2s
                   all         30         68     0.0086      0.993      0.292      0.253

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.87G     0.5745      2.724      1.185          7        640: 100% ━━━━━━━━━━━━ 14/14 5.9it/s 2.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.3it/s 0.2s
                   all         30         68    0.00835      0.986      0.334      0.294

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.87G     0.5963      2.685      1.196          3        640: 100% ━━━━━━━━━━━━ 14/14 6.9it/s 2.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.3it/s 0.2s
                   all         30         68      0.733     0.0895      0.358      0.315

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.87G     0.5763      2.548      1.143          8        640: 100% ━━━━━━━━━━━━ 14/14 6.0it/s 2.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.6it/s 0.2s
                   all         30         68      0.645      0.295      0.374      0.318

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.87G     0.5388      2.408      1.138          8        640: 100% ━━━━━━━━━━━━ 14/14 6.3it/s 2.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.9it/s 0.2s
                   all         30         68      0.614       0.46      0.419      0.364

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.87G     0.5979      2.272      1.138          8        640: 100% ━━━━━━━━━━━━ 14/14 6.3it/s 2.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.8it/s 0.1s
                   all         30         68        0.6      0.393      0.375       0.33

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.87G     0.5977      2.274      1.169          3        640: 100% ━━━━━━━━━━━━ 14/14 7.3it/s 1.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.4it/s 0.2s
                   all         30         68      0.615      0.474      0.408      0.351

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.87G     0.5565      1.995       1.11         11        640: 100% ━━━━━━━━━━━━ 14/14 5.9it/s 2.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.7it/s 0.1s
                   all         30         68      0.735       0.39      0.457        0.4

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      3.87G     0.5408      1.834      1.124         11        640: 100% ━━━━━━━━━━━━ 14/14 6.7it/s 2.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.1it/s 0.2s
                   all         30         68      0.792      0.406      0.477      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.87G     0.5383      1.731        1.1          9        640: 100% ━━━━━━━━━━━━ 14/14 5.5it/s 2.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.4it/s 0.2s
                   all         30         68      0.808      0.419      0.498      0.432

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.87G     0.5359      1.613      1.127          6        640: 100% ━━━━━━━━━━━━ 14/14 7.4it/s 1.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.5it/s 0.2s
                   all         30         68      0.755      0.453      0.513      0.445

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.87G     0.5328      1.525      1.116          9        640: 100% ━━━━━━━━━━━━ 14/14 7.0it/s 2.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.8it/s 0.1s
                   all         30         68      0.456      0.591      0.569       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.87G     0.5272      1.423      1.118          9        640: 100% ━━━━━━━━━━━━ 14/14 7.5it/s 1.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.1it/s 0.1s
                   all         30         68       0.67      0.584        0.6      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.87G     0.5025      1.402      1.096          9        640: 100% ━━━━━━━━━━━━ 14/14 6.7it/s 2.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.7it/s 0.1s
                   all         30         68      0.586      0.618       0.62      0.547

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.87G     0.4982      1.357      1.082          9        640: 100% ━━━━━━━━━━━━ 14/14 7.5it/s 1.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.6it/s 0.1s
                   all         30         68      0.653      0.648       0.64      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      3.87G     0.5075      1.266      1.086         10        640: 100% ━━━━━━━━━━━━ 14/14 6.8it/s 2.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.8it/s 0.1s
                   all         30         68      0.726      0.567      0.644      0.571

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.88G      0.471      1.307      1.069          3        640: 100% ━━━━━━━━━━━━ 14/14 7.3it/s 1.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.2it/s 0.1s
                   all         30         68      0.743      0.571      0.641      0.566

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.89G     0.4723      1.207      1.058          9        640: 100% ━━━━━━━━━━━━ 14/14 6.7it/s 2.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.3it/s 0.2s
                   all         30         68      0.766       0.56      0.648       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.91G     0.5063      1.178       1.08          7        640: 100% ━━━━━━━━━━━━ 14/14 6.7it/s 2.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.3it/s 0.2s
                   all         30         68      0.794      0.499      0.666      0.597

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.93G     0.4791      1.151      1.091          7        640: 100% ━━━━━━━━━━━━ 14/14 6.1it/s 2.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.4it/s 0.2s
                   all         30         68      0.553      0.605      0.663      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.94G     0.4906      1.077      1.084         10        640: 100% ━━━━━━━━━━━━ 14/14 6.8it/s 2.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.4it/s 0.2s
                   all         30         68      0.518       0.71      0.688      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.95G     0.4596      1.119      1.108          4        640: 100% ━━━━━━━━━━━━ 14/14 6.3it/s 2.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.0it/s 0.1s
                   all         30         68       0.56      0.637       0.67      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      3.97G     0.4575      1.054      1.051         13        640: 100% ━━━━━━━━━━━━ 14/14 6.6it/s 2.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.2it/s 0.2s
                   all         30         68      0.627      0.631      0.683      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.98G     0.4638       1.03      1.075          7        640: 100% ━━━━━━━━━━━━ 14/14 5.8it/s 2.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.3it/s 0.2s
                   all         30         68      0.592      0.644      0.665      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50         4G     0.4746      1.029      1.064          8        640: 100% ━━━━━━━━━━━━ 14/14 6.2it/s 2.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.6it/s 0.2s
                   all         30         68      0.817      0.534      0.686        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      4.01G     0.4373      1.004      1.051          6        640: 100% ━━━━━━━━━━━━ 14/14 5.8it/s 2.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.1it/s 0.2s
                   all         30         68      0.813      0.568      0.728      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      4.03G     0.4303     0.9743       1.03         14        640: 100% ━━━━━━━━━━━━ 14/14 6.5it/s 2.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.1it/s 0.2s
                   all         30         68      0.698      0.634      0.716      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      4.04G     0.4369     0.9478      1.028         10        640: 100% ━━━━━━━━━━━━ 14/14 5.7it/s 2.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.9it/s 0.2s
                   all         30         68       0.68      0.685       0.75      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,200,0.760120,0.728120,0.979800,0.963590
2,nano,300,0.812700,0.747497,0.994463,0.988593
3,nano,750,0.930803,0.851967,0.986920,0.965513
4,nano,1000,0.905773,0.839843,0.986080,0.963213
5,nano,1250,0.957177,0.901227,0.989087,0.966697
6,nano,1500,0.964817,0.918633,0.985893,0.964907
7,nano,1750,0.942217,0.894710,0.988663,0.967827
8,nano,2000,0.940753,0.896000,0.988143,0.967657
9,nano,3000,0.960183,0.914897,0.986400,0.964483
10,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png
New https://pypi.org/project/ultralytics/8.4.46 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.0  Python-3.12.12 torch-2.9.1+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 16303MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=split-dataset\400\data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=split_400, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=results\yolo_v12\feedback_reviewer\training\nano, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_400, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1     86912  ultralytics.nn.modules.block.A2C2f           [384, 128, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     24000  ultralytics.nn.modules.block.A2C2f           [256, 64, 1, False, -1]
 15                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     74624  ultralytics.nn.modules.block.A2C2f           [192, 128, 1, False, -1]
 18                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 21        [14, 17, 20]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLOv12n summary: 272 layers, 2,568,633 parameters, 2,568,617 gradients, 6.5 GFLOPs

Transferred 640/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 9.22.2 MB/s, size: 47.3 KB)
train: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\400\train\labels... 280 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 280/280 1.0Kit/s 0.3s<0.1s
train: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\400\train\labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.20.1 ms, read: 5.61.2 MB/s, size: 45.5 KB)
val: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\400\val\labels... 40 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 40/40 507.6it/s 0.1s
val: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\400\val\labels.cache
Plotting labels to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_400\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: MuSGD(lr=0.001429, momentum=0.9) with parameter groups 0 weight(decay=0.0), 0 weight(decay=0.0005), 0 bias(decay=0.0)
MLflow: logging run_id(ce093c1b67ee457d97052f6320cbd94b) to https://dagshub.com/abiyamf/thesis.mlflow
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_400
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      3.91G      1.071      3.196      1.585         30        640: 100% ━━━━━━━━━━━━ 18/18 1.5it/s 11.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.2it/s 1.7s3.1s
                   all         40        115    0.00831      0.932     0.0467     0.0238

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.91G     0.8011      3.068      1.379         37        640: 100% ━━━━━━━━━━━━ 18/18 5.0it/s 3.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.7it/s 0.3s0.6s
                   all         40        115    0.00966      0.956       0.13     0.0778

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.91G     0.6691      2.981      1.274         28        640: 100% ━━━━━━━━━━━━ 18/18 5.1it/s 3.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.9it/s 0.3s0.6s
                   all         40        115     0.0108      0.971      0.245       0.19

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.91G     0.5944      2.843      1.187         33        640: 100% ━━━━━━━━━━━━ 18/18 5.9it/s 3.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.2it/s 0.2s0.5s
                   all         40        115     0.0109      0.971      0.315      0.274

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.91G     0.5716      2.702      1.171         43        640: 100% ━━━━━━━━━━━━ 18/18 5.9it/s 3.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.3it/s 0.2s0.5s
                   all         40        115     0.0107          1      0.331      0.284

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.91G     0.5732       2.53      1.165         31        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.5it/s 0.3s0.6s
                   all         40        115      0.714      0.214      0.363      0.303

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.91G     0.6214      2.411      1.182         26        640: 100% ━━━━━━━━━━━━ 18/18 6.6it/s 2.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.4it/s 0.2s0.6s
                   all         40        115      0.687      0.304      0.414      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.91G     0.5968      2.274      1.163         29        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.9it/s 0.3s0.6s
                   all         40        115       0.82      0.355      0.478       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.91G     0.5866      2.104      1.136         40        640: 100% ━━━━━━━━━━━━ 18/18 6.6it/s 2.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 9.0it/s 0.2s0.5s
                   all         40        115      0.371       0.47      0.474        0.4

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.91G     0.5697      1.948      1.138         37        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.5it/s 0.2s0.5s
                   all         40        115      0.831      0.486      0.549      0.475

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.91G     0.5607      1.749       1.15         45        640: 100% ━━━━━━━━━━━━ 18/18 6.7it/s 2.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 9.1it/s 0.2s0.5s
                   all         40        115      0.825      0.502       0.55      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.91G     0.5904      1.663      1.184         31        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.4it/s 0.2s0.6s
                   all         40        115      0.791       0.52      0.548      0.478

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      3.91G     0.5488      1.569      1.135         43        640: 100% ━━━━━━━━━━━━ 18/18 6.7it/s 2.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.8it/s 0.2s0.5s
                   all         40        115      0.509      0.564      0.559      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.91G     0.5267      1.415      1.098         45        640: 100% ━━━━━━━━━━━━ 18/18 6.1it/s 2.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.5it/s 0.2s0.5s
                   all         40        115       0.84      0.466       0.56      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.91G     0.5417      1.403      1.119         30        640: 100% ━━━━━━━━━━━━ 18/18 6.6it/s 2.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.3it/s 0.2s0.6s
                   all         40        115      0.482      0.621      0.645      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.91G     0.4972      1.298      1.095         30        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.5it/s 0.2s0.6s
                   all         40        115      0.872      0.538      0.671      0.596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.91G     0.5046      1.289      1.083         29        640: 100% ━━━━━━━━━━━━ 18/18 6.8it/s 2.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.9it/s 0.2s0.5s
                   all         40        115      0.537      0.733      0.718      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.91G      0.522      1.221      1.106         31        640: 100% ━━━━━━━━━━━━ 18/18 6.1it/s 3.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.5it/s 0.2s0.5s
                   all         40        115      0.681      0.675      0.751       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.91G     0.5063      1.182       1.09         33        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.7it/s 0.2s0.6s
                   all         40        115      0.775      0.641      0.736      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      3.91G      0.499      1.156       1.09         29        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.1it/s 0.2s0.5s
                   all         40        115      0.618      0.822      0.755       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.91G     0.4592      1.136      1.059         31        640: 100% ━━━━━━━━━━━━ 18/18 6.1it/s 2.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.6it/s 0.2s0.5s
                   all         40        115      0.638      0.792      0.789       0.71

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.91G     0.4774      1.112      1.072         31        640: 100% ━━━━━━━━━━━━ 18/18 6.0it/s 3.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.1it/s 0.2s0.5s
                   all         40        115      0.602      0.791       0.78      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.91G     0.4582      1.006      1.042         35        640: 100% ━━━━━━━━━━━━ 18/18 6.2it/s 2.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.1it/s 0.2s0.6s
                   all         40        115      0.643      0.815        0.8      0.717

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.91G     0.4547      1.016      1.059         30        640: 100% ━━━━━━━━━━━━ 18/18 5.9it/s 3.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.1it/s 0.2s0.5s
                   all         40        115      0.622      0.828      0.793      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.91G     0.4662     0.9972      1.053         33        640: 100% ━━━━━━━━━━━━ 18/18 6.1it/s 2.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.4it/s 0.2s0.5s
                   all         40        115      0.689      0.778      0.792      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.92G     0.4667     0.9905       1.06         27        640: 100% ━━━━━━━━━━━━ 18/18 6.0it/s 3.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.5it/s 0.2s0.5s
                   all         40        115      0.753      0.763      0.791      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      3.93G     0.4776     0.9806       1.07         33        640: 100% ━━━━━━━━━━━━ 18/18 6.4it/s 2.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.4it/s 0.2s0.5s
                   all         40        115      0.852       0.65      0.797      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.95G     0.4578     0.9532      1.056         27        640: 100% ━━━━━━━━━━━━ 18/18 6.0it/s 3.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.6it/s 0.2s0.5s
                   all         40        115      0.766      0.756      0.798      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      3.96G     0.4404     0.9639      1.046         33        640: 100% ━━━━━━━━━━━━ 18/18 6.7it/s 2.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.8it/s 0.2s0.5s
                   all         40        115      0.733      0.777      0.777      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      3.98G     0.4314     0.9184      1.035         29        640: 100% ━━━━━━━━━━━━ 18/18 6.1it/s 2.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.4it/s 0.2s0.6s
                   all         40        115      0.744      0.778      0.766      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      3.99G     0.4279     0.9163       1.04         26        640: 100% ━━━━━━━━━━━━ 18/18 6.5it/s 2.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.9it/s 0.2s0.5s
                   all         40        115      0.686      0.838      0.783        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      4.01G     0.4107     0.8896      1.031         31        640: 100% ━━━━━━━━━━━━ 18/18 6.1it/s 3.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.8it/s 0.2s0.5s

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,200,0.760120,0.728120,0.979800,0.963590
2,nano,300,0.812700,0.747497,0.994463,0.988593
3,nano,400,0.777840,0.714320,0.971670,0.938523
4,nano,750,0.930803,0.851967,0.986920,0.965513
5,nano,1000,0.905773,0.839843,0.986080,0.963213
6,nano,1250,0.957177,0.901227,0.989087,0.966697
7,nano,1500,0.964817,0.918633,0.985893,0.964907
8,nano,1750,0.942217,0.894710,0.988663,0.967827
9,nano,2000,0.940753,0.896000,0.988143,0.967657
10,nano,3000,0.960183,0.914897,0.986400,0.964483
11,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png
New https://pypi.org/project/ultralytics/8.4.46 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.0  Python-3.12.12 torch-2.9.1+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 16303MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=split-dataset\500\data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=split_500, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=results\yolo_v12\feedback_reviewer\training\nano, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_500, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1     86912  ultralytics.nn.modules.block.A2C2f           [384, 128, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     24000  ultralytics.nn.modules.block.A2C2f           [256, 64, 1, False, -1]
 15                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     74624  ultralytics.nn.modules.block.A2C2f           [192, 128, 1, False, -1]
 18                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 21        [14, 17, 20]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLOv12n summary: 272 layers, 2,568,633 parameters, 2,568,617 gradients, 6.5 GFLOPs

Transferred 640/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 9.91.7 MB/s, size: 51.0 KB)
train: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\500\train\labels... 350 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 350/350 637.5it/s 0.5s0.0s
train: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\500\train\labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.30.1 ms, read: 5.51.9 MB/s, size: 48.0 KB)
val: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\500\val\labels... 50 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 50/50 645.9it/s 0.1s
val: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\500\val\labels.cache
Plotting labels to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_500\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: MuSGD(lr=0.001429, momentum=0.9) with parameter groups 0 weight(decay=0.0), 0 weight(decay=0.0005), 0 bias(decay=0.0)
MLflow: logging run_id(b34397a4371f49f681ab787f44abf3d6) to https://dagshub.com/abiyamf/thesis.mlflow
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_500
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      3.95G      1.026      3.179      1.573         74        640: 100% ━━━━━━━━━━━━ 22/22 1.9it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.9it/s 1.1s0.9s
                   all         50        101    0.00586      0.965     0.0638      0.032

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.95G      0.724      3.051      1.337         64        640: 100% ━━━━━━━━━━━━ 22/22 4.5it/s 4.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.9it/s 0.3s0.6s
                   all         50        101    0.00652      0.965      0.159      0.109

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.95G     0.6274      2.917      1.224         53        640: 100% ━━━━━━━━━━━━ 22/22 5.1it/s 4.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.6it/s 0.3s0.6s
                   all         50        101    0.00682       0.98      0.317      0.264

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.95G     0.6022      2.763      1.181         55        640: 100% ━━━━━━━━━━━━ 22/22 5.6it/s 4.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.1it/s 0.3s0.6s
                   all         50        101    0.00709       0.99      0.357      0.309

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.95G     0.5887      2.553      1.162         52        640: 100% ━━━━━━━━━━━━ 22/22 6.0it/s 3.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.7it/s 0.3s0.6s
                   all         50        101      0.608      0.198      0.407      0.336

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.95G     0.6147      2.379      1.169         59        640: 100% ━━━━━━━━━━━━ 22/22 5.6it/s 3.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.9it/s 0.3s0.6s
                   all         50        101      0.396       0.52      0.445      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.95G     0.5952      2.171      1.149         67        640: 100% ━━━━━━━━━━━━ 22/22 5.9it/s 3.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.5it/s 0.3s0.6s
                   all         50        101       0.33      0.602      0.471      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.95G     0.5991      1.985      1.154         65        640: 100% ━━━━━━━━━━━━ 22/22 5.6it/s 3.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.5it/s 0.3s0.6s
                   all         50        101      0.407      0.723      0.542      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.95G     0.5923       1.81       1.15         60        640: 100% ━━━━━━━━━━━━ 22/22 6.1it/s 3.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.3it/s 0.3s0.5s
                   all         50        101      0.541      0.652      0.695      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.95G     0.5602      1.657      1.128         61        640: 100% ━━━━━━━━━━━━ 22/22 5.9it/s 3.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.1it/s 0.3s0.6s
                   all         50        101      0.661      0.796       0.77      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.95G     0.5437      1.514      1.119         47        640: 100% ━━━━━━━━━━━━ 22/22 6.3it/s 3.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.4it/s 0.3s0.6s
                   all         50        101      0.791      0.739      0.778      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.95G     0.5432      1.497      1.125         54        640: 100% ━━━━━━━━━━━━ 22/22 6.0it/s 3.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.9it/s 0.3s0.6s
                   all         50        101      0.794      0.733      0.819      0.728

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      3.95G     0.5284      1.388      1.106         60        640: 100% ━━━━━━━━━━━━ 22/22 6.2it/s 3.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.1it/s 0.3s0.6s
                   all         50        101       0.85       0.74      0.837      0.741

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.95G     0.5168      1.315      1.095         49        640: 100% ━━━━━━━━━━━━ 22/22 6.0it/s 3.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.4it/s 0.3s0.5s
                   all         50        101      0.861      0.723      0.822      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.95G     0.5184      1.306      1.094         57        640: 100% ━━━━━━━━━━━━ 22/22 6.2it/s 3.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.3it/s 0.3s0.5s
                   all         50        101      0.872      0.773       0.84      0.744

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.95G     0.5151      1.216      1.102         62        640: 100% ━━━━━━━━━━━━ 22/22 5.9it/s 3.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.9it/s 0.3s0.6s
                   all         50        101      0.779      0.818      0.863      0.776

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.95G     0.5095      1.222      1.098         73        640: 100% ━━━━━━━━━━━━ 22/22 6.0it/s 3.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.4it/s 0.3s0.6s
                   all         50        101      0.769      0.751       0.84      0.748

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.95G      0.486      1.144      1.069         75        640: 100% ━━━━━━━━━━━━ 22/22 5.3it/s 4.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.5it/s 0.3s0.6s
                   all         50        101      0.875      0.821      0.868      0.803

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.95G     0.4735      1.085      1.058         62        640: 100% ━━━━━━━━━━━━ 22/22 5.8it/s 3.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.0it/s 0.3s0.7s
                   all         50        101      0.836      0.771      0.879       0.81

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      3.95G     0.5041      1.068      1.086         55        640: 100% ━━━━━━━━━━━━ 22/22 4.5it/s 4.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.7it/s 0.3s0.6s
                   all         50        101      0.886      0.806      0.862      0.778

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.95G     0.4876      1.061      1.079         41        640: 100% ━━━━━━━━━━━━ 22/22 5.5it/s 4.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.1it/s 0.3s0.6s
                   all         50        101       0.88      0.831      0.856      0.799

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.95G     0.4784      1.053      1.064         47        640: 100% ━━━━━━━━━━━━ 22/22 5.4it/s 4.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.5it/s 0.3s0.6s
                   all         50        101      0.863      0.858      0.846      0.792

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.95G     0.4727      1.023      1.066         70        640: 100% ━━━━━━━━━━━━ 22/22 5.7it/s 3.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.1it/s 0.3s0.5s
                   all         50        101      0.865      0.835      0.842      0.791

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.95G     0.4603     0.9736      1.059         48        640: 100% ━━━━━━━━━━━━ 22/22 5.6it/s 3.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.5it/s 0.3s0.6s
                   all         50        101      0.772      0.841      0.856      0.804

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.95G     0.4566     0.9963      1.058         63        640: 100% ━━━━━━━━━━━━ 22/22 5.8it/s 3.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.1it/s 0.3s0.5s
                   all         50        101      0.873      0.783      0.854        0.8

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.95G      0.453     0.9331      1.047         60        640: 100% ━━━━━━━━━━━━ 22/22 5.6it/s 3.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.2it/s 0.3s0.5s
                   all         50        101      0.892      0.808      0.865      0.789

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      3.95G      0.442      0.955      1.042         65        640: 100% ━━━━━━━━━━━━ 22/22 5.4it/s 4.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.4it/s 0.3s0.5s
                   all         50        101      0.901      0.785       0.89      0.801

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.95G     0.4645     0.9271      1.053         79        640: 100% ━━━━━━━━━━━━ 22/22 5.7it/s 3.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.4it/s 0.3s0.5s
                   all         50        101      0.893      0.781      0.893      0.821

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      3.95G     0.4494     0.9002      1.033         58        640: 100% ━━━━━━━━━━━━ 22/22 5.8it/s 3.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.4it/s 0.3s0.5s
                   all         50        101      0.785      0.847      0.868      0.796

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      3.95G     0.4298     0.8631      1.026         53        640: 100% ━━━━━━━━━━━━ 22/22 5.5it/s 4.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.2it/s 0.3s0.5s
                   all         50        101      0.814       0.82      0.853      0.782

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      3.96G     0.4288      0.878      1.037         45        640: 100% ━━━━━━━━━━━━ 22/22 5.6it/s 3.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.0it/s 0.3s0.6s
                   all         50        101       0.91      0.799      0.866      0.793

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      3.97G     0.4391     0.8874      1.032         57        640: 100% ━━━━━━━━━━━━ 22/22 5.5it/s 4.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.9it/s 0.3s0.6s

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,200,0.760120,0.728120,0.979800,0.963590
2,nano,300,0.812700,0.747497,0.994463,0.988593
3,nano,400,0.777840,0.714320,0.971670,0.938523
4,nano,500,0.886377,0.853100,0.994750,0.985200
5,nano,750,0.930803,0.851967,0.986920,0.965513
6,nano,1000,0.905773,0.839843,0.986080,0.963213
7,nano,1250,0.957177,0.901227,0.989087,0.966697
8,nano,1500,0.964817,0.918633,0.985893,0.964907
9,nano,1750,0.942217,0.894710,0.988663,0.967827
10,nano,2000,0.940753,0.896000,0.988143,0.967657
11,nano,3000,0.960183,0.914897,0.986400,0.964483
12,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png
New https://pypi.org/project/ultralytics/8.4.46 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.0  Python-3.12.12 torch-2.9.1+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 16303MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=split-dataset\600\data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=split_600, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=results\yolo_v12\feedback_reviewer\training\nano, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_600, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1     86912  ultralytics.nn.modules.block.A2C2f           [384, 128, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     24000  ultralytics.nn.modules.block.A2C2f           [256, 64, 1, False, -1]
 15                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     74624  ultralytics.nn.modules.block.A2C2f           [192, 128, 1, False, -1]
 18                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 21        [14, 17, 20]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLOv12n summary: 272 layers, 2,568,633 parameters, 2,568,617 gradients, 6.5 GFLOPs

Transferred 640/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 7.61.3 MB/s, size: 47.1 KB)
train: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\600\train\labels... 420 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 420/420 999.3it/s 0.4s0.0s
train: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\600\train\labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.30.1 ms, read: 5.21.5 MB/s, size: 47.1 KB)
val: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\600\val\labels... 60 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 60/60 639.3it/s 0.1s
val: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\600\val\labels.cache
Plotting labels to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_600\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: MuSGD(lr=0.001429, momentum=0.9) with parameter groups 0 weight(decay=0.0), 0 weight(decay=0.0005), 0 bias(decay=0.0)
MLflow: logging run_id(3e09482384ee44dba8f7575d49147e51) to https://dagshub.com/abiyamf/thesis.mlflow
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_600
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      3.97G     0.9871      3.181      1.526         21        640: 100% ━━━━━━━━━━━━ 27/27 1.9it/s 14.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.9it/s 1.0s0.8s
                   all         60        123    0.00611      0.988     0.0751     0.0401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.97G     0.7018      2.996      1.298         10        640: 100% ━━━━━━━━━━━━ 27/27 4.7it/s 5.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.1it/s 0.3s0.6s
                   all         60        123    0.00691      0.996      0.248      0.193

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.97G     0.6157      2.827      1.216         17        640: 100% ━━━━━━━━━━━━ 27/27 5.2it/s 5.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.4it/s 0.4s0.7s
                   all         60        123    0.00714          1      0.295      0.257

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.97G     0.6164      2.641      1.192          7        640: 100% ━━━━━━━━━━━━ 27/27 5.6it/s 4.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.7it/s 0.3s0.6s
                   all         60        123      0.652      0.264       0.33      0.288

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.97G     0.6185      2.436      1.183         16        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.8it/s 0.3s0.6s
                   all         60        123      0.615      0.489       0.36      0.317

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.97G     0.6419      2.181      1.177         22        640: 100% ━━━━━━━━━━━━ 27/27 5.7it/s 4.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.6it/s 0.4s0.7s
                   all         60        123      0.734      0.408      0.454      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.97G     0.6405      1.984      1.191         23        640: 100% ━━━━━━━━━━━━ 27/27 5.6it/s 4.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.6it/s 0.4s0.6s
                   all         60        123      0.809       0.45      0.507      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.97G     0.5806      1.783      1.157         18        640: 100% ━━━━━━━━━━━━ 27/27 5.4it/s 5.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.8it/s 0.3s0.6s
                   all         60        123      0.794      0.561      0.603      0.551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.97G     0.5537      1.583      1.121         21        640: 100% ━━━━━━━━━━━━ 27/27 5.7it/s 4.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.9it/s 0.3s0.6s
                   all         60        123      0.602      0.707      0.686       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.97G     0.5643      1.491      1.133         16        640: 100% ━━━━━━━━━━━━ 27/27 5.7it/s 4.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.0it/s 0.3s0.6s
                   all         60        123      0.642      0.773      0.735       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.97G     0.5416      1.403      1.114         17        640: 100% ━━━━━━━━━━━━ 27/27 5.6it/s 4.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.0it/s 0.3s0.6s
                   all         60        123      0.686      0.703      0.766      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.97G     0.5428      1.298      1.122         18        640: 100% ━━━━━━━━━━━━ 27/27 5.7it/s 4.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s0.7s
                   all         60        123      0.719      0.744       0.79       0.74

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      3.97G     0.5248       1.29      1.105         14        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.7it/s 0.3s0.6s
                   all         60        123      0.723      0.761      0.791      0.712

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.97G     0.5083      1.226      1.099         11        640: 100% ━━━━━━━━━━━━ 27/27 6.5it/s 4.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.1it/s 0.3s0.5s
                   all         60        123      0.662      0.858      0.816      0.753

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.97G     0.5014      1.151      1.077         15        640: 100% ━━━━━━━━━━━━ 27/27 6.3it/s 4.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.4it/s 0.4s0.7s
                   all         60        123      0.731       0.79      0.809      0.758

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.97G     0.4886      1.112      1.082         14        640: 100% ━━━━━━━━━━━━ 27/27 5.4it/s 5.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.4it/s 0.3s0.6s
                   all         60        123      0.705        0.7      0.677      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.97G     0.4977      1.094      1.082         17        640: 100% ━━━━━━━━━━━━ 27/27 6.0it/s 4.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.4it/s 0.3s0.6s
                   all         60        123      0.758      0.717      0.776      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.97G      0.494      1.062      1.078         17        640: 100% ━━━━━━━━━━━━ 27/27 5.8it/s 4.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.1it/s 0.3s0.6s
                   all         60        123      0.716      0.762      0.763      0.721

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.97G     0.5045      1.107      1.095         18        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.2it/s 0.3s0.6s
                   all         60        123      0.757      0.765       0.84      0.785

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      3.97G     0.4781      1.055       1.07         22        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.7it/s 0.3s0.5s
                   all         60        123      0.837      0.772       0.85      0.802

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.97G     0.4795      1.015      1.077         14        640: 100% ━━━━━━━━━━━━ 27/27 6.1it/s 4.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s0.6s
                   all         60        123      0.757      0.792      0.834      0.798

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.97G     0.4657     0.9892      1.055         18        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.2it/s 0.3s0.6s
                   all         60        123      0.774      0.758      0.825      0.777

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.97G     0.4907     0.9809      1.075         13        640: 100% ━━━━━━━━━━━━ 27/27 6.0it/s 4.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.2it/s 0.3s0.6s
                   all         60        123      0.801      0.753      0.829      0.794

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.97G     0.4605     0.9419      1.047         16        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s0.6s
                   all         60        123      0.768      0.764        0.8      0.761

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.97G     0.4574     0.9007      1.046         21        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s0.5s
                   all         60        123      0.783      0.837       0.85      0.812

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.97G     0.4566      0.926       1.06         22        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s0.6s
                   all         60        123      0.806      0.718      0.847      0.814

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      3.97G     0.4498     0.8742      1.041         12        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s0.6s
                   all         60        123      0.798      0.724       0.85      0.819

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.98G       0.43     0.8984      1.034         23        640: 100% ━━━━━━━━━━━━ 27/27 6.0it/s 4.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.4it/s 0.3s0.5s
                   all         60        123      0.773      0.776      0.855      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50         4G     0.4291     0.8629      1.034         11        640: 100% ━━━━━━━━━━━━ 27/27 6.2it/s 4.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s0.6s
                   all         60        123      0.789      0.765      0.863      0.838

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      4.02G     0.4465     0.9072      1.058         15        640: 100% ━━━━━━━━━━━━ 27/27 5.8it/s 4.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.4it/s 0.3s0.5s
                   all         60        123      0.807        0.8      0.874      0.839

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      4.02G      0.433     0.8374      1.027         11        640: 100% ━━━━━━━━━━━━ 27/27 5.8it/s 4.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s0.5s
                   all         60        123      0.783      0.839      0.876      0.837

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      4.05G     0.4505     0.8617      1.054         13        640: 100% ━━━━━━━━━━━━ 27/27 5.9it/s 4.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.4it/s 0.3s0.5s

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,200,0.760120,0.728120,0.979800,0.963590
2,nano,300,0.812700,0.747497,0.994463,0.988593
3,nano,400,0.777840,0.714320,0.971670,0.938523
4,nano,500,0.886377,0.853100,0.994750,0.985200
5,nano,600,0.926467,0.885897,0.994940,0.987093
6,nano,750,0.930803,0.851967,0.986920,0.965513
7,nano,1000,0.905773,0.839843,0.986080,0.963213
8,nano,1250,0.957177,0.901227,0.989087,0.966697
9,nano,1500,0.964817,0.918633,0.985893,0.964907
10,nano,1750,0.942217,0.894710,0.988663,0.967827
11,nano,2000,0.940753,0.896000,0.988143,0.967657
12,nano,3000,0.960183,0.914897,0.986400,0.964483
13,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png
New https://pypi.org/project/ultralytics/8.4.46 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.0  Python-3.12.12 torch-2.9.1+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 16303MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=split-dataset\700\data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=split_700, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=results\yolo_v12\feedback_reviewer\training\nano, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_700, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 10             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 11                  -1  1     86912  ultralytics.nn.modules.block.A2C2f           [384, 128, 1, False, -1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1     24000  ultralytics.nn.modules.block.A2C2f           [256, 64, 1, False, -1]
 15                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 16            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     74624  ultralytics.nn.modules.block.A2C2f           [192, 128, 1, False, -1]
 18                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 19             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 21        [14, 17, 20]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLOv12n summary: 272 layers, 2,568,633 parameters, 2,568,617 gradients, 6.5 GFLOPs

Transferred 640/691 items from pretrained weights
Freezing layer 'model.21.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 8.63.0 MB/s, size: 51.1 KB)
train: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\700\train\labels... 489 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 489/489 873.1it/s 0.6s0.1s
train: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\700\train\labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access  (ping: 0.30.1 ms, read: 6.71.2 MB/s, size: 46.2 KB)
val: Scanning C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\700\val\labels... 70 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 70/70 648.6it/s 0.1s0.0s
val: New cache created: C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\split-dataset\700\val\labels.cache
Plotting labels to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_700\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: MuSGD(lr=0.001429, momentum=0.9) with parameter groups 0 weight(decay=0.0), 0 weight(decay=0.0005), 0 bias(decay=0.0)
MLflow: logging run_id(0ba75aa595374fc387f73eb8883b21f0) to https://dagshub.com/abiyamf/thesis.mlflow
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\abiyamf\Documents\Code Program\Thesis\new_experiment_for_feedback_reviewer\runs\detect\results\yolo_v12\feedback_reviewer\training\nano\split_700
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      3.99G      1.007      3.166      1.535         39        640: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 17.9s0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.5it/s 1.2s0.4s
                   all         70        124    0.00541      0.966      0.115     0.0704

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.99G     0.6594      2.974      1.267         40        640: 100% ━━━━━━━━━━━━ 31/31 4.7it/s 6.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.4s
                   all         70        124    0.00682      0.983      0.264      0.222

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.99G     0.6007      2.771      1.185         29        640: 100% ━━━━━━━━━━━━ 31/31 5.3it/s 5.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.1it/s 0.4s0.3s
                   all         70        124      0.586      0.432      0.318      0.283

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.99G     0.6227       2.53      1.192         48        640: 100% ━━━━━━━━━━━━ 31/31 5.3it/s 5.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.4it/s 0.6s0.4s
                   all         70        124      0.262      0.486      0.345        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.99G     0.6158      2.278      1.174         35        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.4it/s 0.4s0.3s
                   all         70        124      0.633      0.443      0.374      0.331

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.99G     0.6251      2.058       1.19         36        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.6it/s 0.4s0.3s
                   all         70        124      0.308      0.629      0.512      0.472

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.99G      0.609       1.79      1.165         32        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.4it/s 0.4s0.3s
                   all         70        124      0.522      0.585       0.56      0.517

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.99G     0.5813       1.59      1.159         43        640: 100% ━━━━━━━━━━━━ 31/31 5.8it/s 5.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.4it/s 0.4s0.3s
                   all         70        124      0.547      0.726      0.675      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.99G     0.5488       1.48      1.126         36        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.2it/s 0.4s0.3s
                   all         70        124      0.626      0.697      0.711      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.99G     0.5496       1.38      1.128         35        640: 100% ━━━━━━━━━━━━ 31/31 5.5it/s 5.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.5it/s 0.4s0.3s
                   all         70        124      0.734      0.711      0.749      0.711

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.99G      0.525       1.28      1.106         37        640: 100% ━━━━━━━━━━━━ 31/31 5.3it/s 5.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s0.3s
                   all         70        124      0.777      0.667      0.753       0.72

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.99G      0.539      1.303      1.116         53        640: 100% ━━━━━━━━━━━━ 31/31 5.7it/s 5.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.5it/s 0.4s0.3s
                   all         70        124      0.687      0.779      0.767      0.737

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      3.99G     0.5105      1.182      1.088         34        640: 100% ━━━━━━━━━━━━ 31/31 6.7it/s 4.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.3it/s 0.4s0.3s
                   all         70        124      0.703      0.805      0.841      0.781

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.99G      0.493      1.143      1.088         44        640: 100% ━━━━━━━━━━━━ 31/31 5.6it/s 5.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.5it/s 0.4s0.3s
                   all         70        124      0.684      0.834       0.87      0.809

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.99G      0.491      1.125      1.083         38        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s0.3s
                   all         70        124      0.833      0.799      0.873      0.822

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.99G     0.5181        1.1      1.099         31        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.6it/s 0.4s0.3s
                   all         70        124      0.816      0.878      0.898      0.841

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.99G     0.5084      1.063      1.081         37        640: 100% ━━━━━━━━━━━━ 31/31 6.1it/s 5.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.7it/s 0.4s0.3s
                   all         70        124      0.823      0.831      0.889      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.99G     0.4888      1.044      1.078         32        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s0.3s
                   all         70        124      0.843        0.8      0.884      0.855

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.99G     0.4676     0.9884      1.066         40        640: 100% ━━━━━━━━━━━━ 31/31 6.0it/s 5.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.8it/s 0.4s0.3s
                   all         70        124      0.786      0.865      0.918      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      3.99G     0.4959     0.9967      1.079         40        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.6it/s 0.4s0.3s
                   all         70        124       0.82      0.866      0.909      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.99G     0.4616     0.9679      1.053         31        640: 100% ━━━━━━━━━━━━ 31/31 6.2it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.0it/s 0.4s0.3s
                   all         70        124      0.828      0.878      0.911      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.99G     0.4663      0.932      1.066         33        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.6it/s 0.4s0.3s
                   all         70        124      0.829      0.889      0.922      0.887

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.99G      0.469     0.9198      1.056         44        640: 100% ━━━━━━━━━━━━ 31/31 6.0it/s 5.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.5it/s 0.4s0.3s
                   all         70        124      0.903        0.8      0.899      0.869

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.99G     0.4532     0.9191      1.045         45        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.8it/s 0.4s0.3s
                   all         70        124      0.867      0.857      0.894      0.864

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.99G     0.4354     0.8478      1.048         32        640: 100% ━━━━━━━━━━━━ 31/31 6.2it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.0it/s 0.4s0.3s
                   all         70        124      0.872      0.805      0.913      0.886

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.99G     0.4339     0.9067      1.049         41        640: 100% ━━━━━━━━━━━━ 31/31 5.9it/s 5.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s0.3s
                   all         70        124      0.862      0.876      0.925      0.896

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      3.99G     0.4454     0.8725      1.047         34        640: 100% ━━━━━━━━━━━━ 31/31 6.1it/s 5.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s0.3s
                   all         70        124      0.757      0.918      0.916      0.875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.99G     0.4433     0.8892      1.046         45        640: 100% ━━━━━━━━━━━━ 31/31 6.0it/s 5.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s0.3s
                   all         70        124      0.785      0.913      0.907      0.884

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      3.99G     0.4401     0.8327      1.042         36        640: 100% ━━━━━━━━━━━━ 31/31 6.1it/s 5.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.9it/s 0.4s0.3s
                   all         70        124      0.832      0.882      0.906      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      3.99G     0.4454     0.8217      1.041         34        640: 100% ━━━━━━━━━━━━ 31/31 6.1it/s 5.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.0it/s 0.4s0.3s
                   all         70        124      0.812      0.848      0.905      0.875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50         4G     0.4181     0.8147      1.038         50        640: 100% ━━━━━━━━━━━━ 31/31 5.7it/s 5.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.7it/s 0.4s0.3s
                   all         70        124      0.869       0.89      0.929      0.893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      4.02G     0.4356      0.804      1.039         41        640: 100% ━━━━━━━━━━━━ 31/31 5.7it/s 5.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s0.3s

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,200,0.760120,0.728120,0.979800,0.963590
2,nano,300,0.812700,0.747497,0.994463,0.988593
3,nano,400,0.777840,0.714320,0.971670,0.938523
4,nano,500,0.886377,0.853100,0.994750,0.985200
5,nano,600,0.926467,0.885897,0.994940,0.987093
6,nano,700,0.871577,0.811190,0.994790,0.982183
7,nano,750,0.930803,0.851967,0.986920,0.965513
8,nano,1000,0.905773,0.839843,0.986080,0.963213
9,nano,1250,0.957177,0.901227,0.989087,0.966697
10,nano,1500,0.964817,0.918633,0.985893,0.964907
11,nano,1750,0.942217,0.894710,0.988663,0.967827
12,nano,2000,0.940753,0.896000,0.988143,0.967657
13,nano,3000,0.960183,0.914897,0.986400,0.964483
14,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png

In [10]:
# Jalankan cell ini kapan pun setelah notebook berhenti/restart untuk membuat ulang visualisasi
# dari semua file metrik split yang sudah selesai.
summary_df = build_summary_from_validation_files(project_base)
save_and_plot_summary(summary_df, project_base)

,model_size,split_size,test_mAP50,test_mAP50_95,train_mAP50,train_mAP50_95
0,nano,100,0.576887,0.540873,0.632073,0.618650
1,nano,200,0.760120,0.728120,0.979800,0.963590
2,nano,300,0.812700,0.747497,0.994463,0.988593
3,nano,400,0.777840,0.714320,0.971670,0.938523
4,nano,500,0.886377,0.853100,0.994750,0.985200
5,nano,600,0.926467,0.885897,0.994940,0.987093
6,nano,700,0.871577,0.811190,0.994790,0.982183
7,nano,750,0.930803,0.851967,0.986920,0.965513
8,nano,1000,0.905773,0.839843,0.986080,0.963213
9,nano,1250,0.957177,0.901227,0.989087,0.966697
10,nano,1500,0.964817,0.918633,0.985893,0.964907
11,nano,1750,0.942217,0.894710,0.988663,0.967827
12,nano,2000,0.940753,0.896000,0.988143,0.967657
13,nano,3000,0.960183,0.914897,0.986400,0.964483
14,nano,4000,0.958583,0.916713,0.986573,0.966497

Ringkasan disimpan ke: results\yolo_v12\feedback_reviewer\training_summary_by_split.csv
Plot akurasi disimpan ke: results\yolo_v12\feedback_reviewer\accuracy_by_split.png